from fvcore.common.config import CfgNode as CN


def add_impact_data_config(cfg):
    _C = cfg

    _C.IMPACT_DATA = CN()
    _C.IMPACT_DATA.GT_IOU_THRESH = 0.3
    _C.IMPACT_DATA.DETECTION_SCORE_THRESH = 0.5
    _C.IMPACT_DATA.IMG_PROC_BACKEND = "cv2"
    _C.IMPACT_DATA.TRAIN_USE_COLOR_AUGMENTATION = False
    _C.IMPACT_DATA.BGR = True
    _C.IMPACT_DATA.IMPACT_EXTENSION_DELTA = 2
    _C.IMPACT_DATA.MIN_BOX_AREA = 64

    _C.IMPACT_DATA.CENTER_MASK = CN()
    _C.IMPACT_DATA.CENTER_MASK.ENABLED = False
    _C.IMPACT_DATA.CENTER_MASK.MIN_OVERLAP = 0.7

    _C.IMPACT_DATA.TRACKER = CN()
    _C.IMPACT_DATA.TRACKER.SIGMA_L = 0.5
    _C.IMPACT_DATA.TRACKER.SIGMA_H = 0.9
    _C.IMPACT_DATA.TRACKER.SIGMA_IOU = 0.5
    _C.IMPACT_DATA.TRACKER.T_MIN = 1

    _C.IMPACT_DATA.TEST_CROP_SCALE = 5.0
    _C.IMPACT_DATA.TRAIN_JITTER_CROP_SCALES = [4.0, 6.0]
    _C.IMPACT_DATA.TRAIN_JITTER_CROP_CENTER = [-0.0625, 0.0625]
    _C.IMPACT_DATA.IMPACT_RATIO = None
