TRAIN:
  ENABLE: True
  DATASET: impactDataset
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: path to the pretrain checkpoint file.
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 20
  SAMPLING_RATE: 1
  TRAIN_JITTER_SCALES: [640, 800]
  TRAIN_CROP_SIZE: 512
  TEST_CROP_SIZE: 704
  INPUT_CHANNEL_NUM: [3, 3]
  RANDOM_FLIP: True
DETECTION:
  ENABLE: True
  ALIGNED: True
  SPATIAL_SCALE_FACTOR: 2
IMPACT_DATA:
  IMPACT_EXTENSION_DELTA: 2
  GT_IOU_THRESH: 0.35
  IMG_PROC_BACKEND: "cv2"
  TRAIN_USE_COLOR_AUGMENTATION: True
  BGR: False
  MIN_BOX_AREA: 64
  IMPACT_RATIO: 0.25
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0]
  LRS: [1]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 1
  ARCH: slowfast
  MODEL_NAME: SlowFastDeconv
  LOSS_FUNC: bce
  HEAD_ACT: sigmoid
TEST:
  ENABLE: False
  DATASET: impactDataset
  BATCH_SIZE: 16
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "./impact_detector"
TENSORBOARD:
  ENABLE: True
