TRAIN:
  ENABLE: True
  DATASET: impactCropDataset
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 20
  SAMPLING_RATE: 1
  TRAIN_CROP_SIZE: 128
  TEST_CROP_SIZE: 128
  INPUT_CHANNEL_NUM: [5, 5]
  MEAN: [0.45, 0.45, 0.45, 0.0, 0.0]
  STD: [0.225, 0.225, 0.225, 1.0, 1.0]
  RANDOM_FLIP: True
IMPACT_DATA:
  IMPACT_EXTENSION_DELTA: 2
  GT_IOU_THRESH: 0.35
  IMG_PROC_BACKEND: "cv2"
  IMPACT_RATIO: 0.1
  TEST_CROP_SCALE: 5.0
  TRAIN_JITTER_CROP_SCALES: [4.0, 6.0]
  TRAIN_JITTER_CROP_CENTER: [-0.1, 0.1]
  TRAIN_USE_COLOR_AUGMENTATION: True
  CENTER_MASK:
    ENABLED: True
    MIN_OVERLAP: 0.7
  TRACKER:
    SIGMA_L: 0.5
    SIGMA_H: 0.9
    SIGMA_IOU: 0.5
    T_MIN: 1
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10]
  LRS: [1, 0.1]
  MAX_EPOCH: 12
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 1
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce_logit
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: impactCropDataset
  BATCH_SIZE: 128
DATA_LOADER:
  NUM_WORKERS: 6
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "./impact_classifier"
LOG_MODEL_INFO: False
TENSORBOARD:
  ENABLE: True
